import { Injectable } from '@nestjs/common';
import { Model, PaginateModel, Document, FilterQuery } from 'mongoose';
import { InjectModel } from '@nestjs/mongoose';

import CreateCountryDto from '../dto/country.dto';
import { Country } from '../interfaces/country.interface';
import { COUNTRY } from '@rem/shared/constants/schema';
import { StatesService } from './state.service';
import { CountryDocument } from 'countries/schema/country.schema';

type countryModel<T extends Document> = PaginateModel<T>;

@Injectable()
export default class CountriesService {
  constructor(
    @InjectModel(COUNTRY)
    private readonly country: Model<CountryDocument>,
    @InjectModel(COUNTRY)
    private readonly countryPaginated: countryModel<Country>,
    private stateService: StatesService,
  ) {}

  /**
   * Get all paginated countries
   * @param query
   */
  async index(query: any = {}, offset = 0, limit = 10): Promise<any> {
    const customLabels = {
      docs: 'nodes',
      page: 'currentPage',
      totalPages: 'pageCount',
      limit: 'perPage',
      totalDocs: 'itemCount',
    };
    return this.countryPaginated.paginate(query, {
      customLabels,
      offset,
      limit,
    });
  }

  /**
   * Get all countries
   * @param query
   */
  async all(): Promise<Country[]> {
    return this.country.find().sort({ name: 1 });
  }

  /**
   * Create country
   * @param createTransactionDto
   */
  async create(createCountryDto: CreateCountryDto): Promise<Country> {
    createCountryDto.imageUrl = `https://flagcdn.com/64x48/${createCountryDto.iso2}.png`;
    const check = await this.country.findOne({ name: createCountryDto.name });
    if (check) {
      return this.country.findOneAndUpdate(
        { name: createCountryDto.name },
        createCountryDto,
        { new: true },
      );
    }
    // eslint-disable-next-line new-cap
    const country = new this.country(createCountryDto);

    return country.save();
  }

  async getOne(query: FilterQuery<Country> = {}): Promise<Country> {
    return this.country.findOne(query);
  }

  async lookUp() {
    const data = [
      {
        countryCode: 'CI',
        countryName: "Côte d'Ivoire",
        zoneName: 'Africa/Abidjan',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'GH',
        countryName: 'Ghana',
        zoneName: 'Africa/Accra',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'ET',
        countryName: 'Ethiopia',
        zoneName: 'Africa/Addis_Ababa',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'DZ',
        countryName: 'Algeria',
        zoneName: 'Africa/Algiers',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'ER',
        countryName: 'Eritrea',
        zoneName: 'Africa/Asmara',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'ML',
        countryName: 'Mali',
        zoneName: 'Africa/Bamako',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'CF',
        countryName: 'Central African Republic',
        zoneName: 'Africa/Bangui',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'GM',
        countryName: 'Gambia',
        zoneName: 'Africa/Banjul',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'GW',
        countryName: 'Guinea-Bissau',
        zoneName: 'Africa/Bissau',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'MW',
        countryName: 'Malawi',
        zoneName: 'Africa/Blantyre',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'CG',
        countryName: 'Congo',
        zoneName: 'Africa/Brazzaville',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'BI',
        countryName: 'Burundi',
        zoneName: 'Africa/Bujumbura',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'EG',
        countryName: 'Egypt',
        zoneName: 'Africa/Cairo',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'MA',
        countryName: 'Morocco',
        zoneName: 'Africa/Casablanca',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'ES',
        countryName: 'Spain',
        zoneName: 'Africa/Ceuta',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'GN',
        countryName: 'Guinea',
        zoneName: 'Africa/Conakry',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'SN',
        countryName: 'Senegal',
        zoneName: 'Africa/Dakar',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'TZ',
        countryName: 'Tanzania, United Republic of',
        zoneName: 'Africa/Dar_es_Salaam',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'DJ',
        countryName: 'Djibouti',
        zoneName: 'Africa/Djibouti',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'CM',
        countryName: 'Cameroon',
        zoneName: 'Africa/Douala',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'EH',
        countryName: 'Western Sahara',
        zoneName: 'Africa/El_Aaiun',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'SL',
        countryName: 'Sierra Leone',
        zoneName: 'Africa/Freetown',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'BW',
        countryName: 'Botswana',
        zoneName: 'Africa/Gaborone',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'ZW',
        countryName: 'Zimbabwe',
        zoneName: 'Africa/Harare',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'ZA',
        countryName: 'South Africa',
        zoneName: 'Africa/Johannesburg',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'SS',
        countryName: 'South Sudan',
        zoneName: 'Africa/Juba',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'UG',
        countryName: 'Uganda',
        zoneName: 'Africa/Kampala',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'SD',
        countryName: 'Sudan',
        zoneName: 'Africa/Khartoum',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'RW',
        countryName: 'Rwanda',
        zoneName: 'Africa/Kigali',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'CD',
        countryName: 'Congo, Democratic Republic of the',
        zoneName: 'Africa/Kinshasa',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'NG',
        countryName: 'Nigeria',
        zoneName: 'Africa/Lagos',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'GA',
        countryName: 'Gabon',
        zoneName: 'Africa/Libreville',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'TG',
        countryName: 'Togo',
        zoneName: 'Africa/Lome',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'AO',
        countryName: 'Angola',
        zoneName: 'Africa/Luanda',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'CD',
        countryName: 'Congo, Democratic Republic of the',
        zoneName: 'Africa/Lubumbashi',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'ZM',
        countryName: 'Zambia',
        zoneName: 'Africa/Lusaka',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'GQ',
        countryName: 'Equatorial Guinea',
        zoneName: 'Africa/Malabo',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'MZ',
        countryName: 'Mozambique',
        zoneName: 'Africa/Maputo',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'LS',
        countryName: 'Lesotho',
        zoneName: 'Africa/Maseru',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'SZ',
        countryName: 'Eswatini',
        zoneName: 'Africa/Mbabane',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'SO',
        countryName: 'Somalia',
        zoneName: 'Africa/Mogadishu',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'LR',
        countryName: 'Liberia',
        zoneName: 'Africa/Monrovia',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'KE',
        countryName: 'Kenya',
        zoneName: 'Africa/Nairobi',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'TD',
        countryName: 'Chad',
        zoneName: 'Africa/Ndjamena',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'NE',
        countryName: 'Niger',
        zoneName: 'Africa/Niamey',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'MR',
        countryName: 'Mauritania',
        zoneName: 'Africa/Nouakchott',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'BF',
        countryName: 'Burkina Faso',
        zoneName: 'Africa/Ouagadougou',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'BJ',
        countryName: 'Benin',
        zoneName: 'Africa/Porto-Novo',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'ST',
        countryName: 'Sao Tome and Principe',
        zoneName: 'Africa/Sao_Tome',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'LY',
        countryName: 'Libya',
        zoneName: 'Africa/Tripoli',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'TN',
        countryName: 'Tunisia',
        zoneName: 'Africa/Tunis',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'NA',
        countryName: 'Namibia',
        zoneName: 'Africa/Windhoek',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Adak',
        gmtOffset: -32400,
        timestamp: 1647385795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Anchorage',
        gmtOffset: -28800,
        timestamp: 1647389395,
      },
      {
        countryCode: 'AI',
        countryName: 'Anguilla',
        zoneName: 'America/Anguilla',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'AG',
        countryName: 'Antigua and Barbuda',
        zoneName: 'America/Antigua',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Araguaina',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Buenos_Aires',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Catamarca',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Cordoba',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Jujuy',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/La_Rioja',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Mendoza',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Rio_Gallegos',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Salta',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/San_Juan',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/San_Luis',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Tucuman',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        zoneName: 'America/Argentina/Ushuaia',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AW',
        countryName: 'Aruba',
        zoneName: 'America/Aruba',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'PY',
        countryName: 'Paraguay',
        zoneName: 'America/Asuncion',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Atikokan',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Bahia',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Bahia_Banderas',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'BB',
        countryName: 'Barbados',
        zoneName: 'America/Barbados',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Belem',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'BZ',
        countryName: 'Belize',
        zoneName: 'America/Belize',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Blanc-Sablon',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Boa_Vista',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CO',
        countryName: 'Colombia',
        zoneName: 'America/Bogota',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Boise',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Cambridge_Bay',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Campo_Grande',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Cancun',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'VE',
        countryName: 'Venezuela (Bolivarian Republic of)',
        zoneName: 'America/Caracas',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'GF',
        countryName: 'French Guiana',
        zoneName: 'America/Cayenne',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'KY',
        countryName: 'Cayman Islands',
        zoneName: 'America/Cayman',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Chicago',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Chihuahua',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'CR',
        countryName: 'Costa Rica',
        zoneName: 'America/Costa_Rica',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Creston',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Cuiaba',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CW',
        countryName: 'Curaçao',
        zoneName: 'America/Curacao',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'GL',
        countryName: 'Greenland',
        zoneName: 'America/Danmarkshavn',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Dawson',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Dawson_Creek',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Denver',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Detroit',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'DM',
        countryName: 'Dominica',
        zoneName: 'America/Dominica',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Edmonton',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Eirunepe',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'SV',
        countryName: 'El Salvador',
        zoneName: 'America/El_Salvador',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Fort_Nelson',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Fortaleza',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Glace_Bay',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Goose_Bay',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'TC',
        countryName: 'Turks and Caicos Islands',
        zoneName: 'America/Grand_Turk',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'GD',
        countryName: 'Grenada',
        zoneName: 'America/Grenada',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'GP',
        countryName: 'Guadeloupe',
        zoneName: 'America/Guadeloupe',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'GT',
        countryName: 'Guatemala',
        zoneName: 'America/Guatemala',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'EC',
        countryName: 'Ecuador',
        zoneName: 'America/Guayaquil',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'GY',
        countryName: 'Guyana',
        zoneName: 'America/Guyana',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Halifax',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CU',
        countryName: 'Cuba',
        zoneName: 'America/Havana',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Hermosillo',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Indianapolis',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Knox',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Marengo',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Petersburg',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Tell_City',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Vevay',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Vincennes',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Indiana/Winamac',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Inuvik',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Iqaluit',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'JM',
        countryName: 'Jamaica',
        zoneName: 'America/Jamaica',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Juneau',
        gmtOffset: -28800,
        timestamp: 1647389395,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Kentucky/Louisville',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Kentucky/Monticello',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BQ',
        countryName: 'Bonaire, Sint Eustatius and Saba',
        zoneName: 'America/Kralendijk',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BO',
        countryName: 'Bolivia (Plurinational State of)',
        zoneName: 'America/La_Paz',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'PE',
        countryName: 'Peru',
        zoneName: 'America/Lima',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Los_Angeles',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'SX',
        countryName: 'Sint Maarten (Dutch part)',
        zoneName: 'America/Lower_Princes',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Maceio',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'NI',
        countryName: 'Nicaragua',
        zoneName: 'America/Managua',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Manaus',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'MF',
        countryName: 'Saint Martin (French part)',
        zoneName: 'America/Marigot',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'MQ',
        countryName: 'Martinique',
        zoneName: 'America/Martinique',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Matamoros',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Mazatlan',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Menominee',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Merida',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Metlakatla',
        gmtOffset: -28800,
        timestamp: 1647389395,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Mexico_City',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'PM',
        countryName: 'Saint Pierre and Miquelon',
        zoneName: 'America/Miquelon',
        gmtOffset: -7200,
        timestamp: 1647410995,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Moncton',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Monterrey',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'UY',
        countryName: 'Uruguay',
        zoneName: 'America/Montevideo',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'MS',
        countryName: 'Montserrat',
        zoneName: 'America/Montserrat',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BS',
        countryName: 'Bahamas',
        zoneName: 'America/Nassau',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/New_York',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Nipigon',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Nome',
        gmtOffset: -28800,
        timestamp: 1647389395,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Noronha',
        gmtOffset: -7200,
        timestamp: 1647410995,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/North_Dakota/Beulah',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/North_Dakota/Center',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/North_Dakota/New_Salem',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'GL',
        countryName: 'Greenland',
        zoneName: 'America/Nuuk',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Ojinaga',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'PA',
        countryName: 'Panama',
        zoneName: 'America/Panama',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Pangnirtung',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'SR',
        countryName: 'Suriname',
        zoneName: 'America/Paramaribo',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Phoenix',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'HT',
        countryName: 'Haiti',
        zoneName: 'America/Port-au-Prince',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'TT',
        countryName: 'Trinidad and Tobago',
        zoneName: 'America/Port_of_Spain',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Porto_Velho',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'PR',
        countryName: 'Puerto Rico',
        zoneName: 'America/Puerto_Rico',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CL',
        countryName: 'Chile',
        zoneName: 'America/Punta_Arenas',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Rainy_River',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Rankin_Inlet',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Recife',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Regina',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Resolute',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Rio_Branco',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Santarem',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CL',
        countryName: 'Chile',
        zoneName: 'America/Santiago',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'DO',
        countryName: 'Dominican Republic',
        zoneName: 'America/Santo_Domingo',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        zoneName: 'America/Sao_Paulo',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'GL',
        countryName: 'Greenland',
        zoneName: 'America/Scoresbysund',
        gmtOffset: -3600,
        timestamp: 1647414595,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Sitka',
        gmtOffset: -28800,
        timestamp: 1647389395,
      },
      {
        countryCode: 'BL',
        countryName: 'Saint Barthélemy',
        zoneName: 'America/St_Barthelemy',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/St_Johns',
        gmtOffset: -9000,
        timestamp: 1647409195,
      },
      {
        countryCode: 'KN',
        countryName: 'Saint Kitts and Nevis',
        zoneName: 'America/St_Kitts',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'LC',
        countryName: 'Saint Lucia',
        zoneName: 'America/St_Lucia',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'VI',
        countryName: 'Virgin Islands (U.S.)',
        zoneName: 'America/St_Thomas',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'VC',
        countryName: 'Saint Vincent and the Grenadines',
        zoneName: 'America/St_Vincent',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Swift_Current',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'HN',
        countryName: 'Honduras',
        zoneName: 'America/Tegucigalpa',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'GL',
        countryName: 'Greenland',
        zoneName: 'America/Thule',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Thunder_Bay',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        zoneName: 'America/Tijuana',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Toronto',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'VG',
        countryName: 'Virgin Islands (British)',
        zoneName: 'America/Tortola',
        gmtOffset: -14400,
        timestamp: 1647403795,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Vancouver',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Whitehorse',
        gmtOffset: -25200,
        timestamp: 1647392995,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Winnipeg',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'America/Yakutat',
        gmtOffset: -28800,
        timestamp: 1647389395,
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        zoneName: 'America/Yellowknife',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Casey',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Davis',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/DumontDUrville',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Antarctica/Macquarie',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Mawson',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/McMurdo',
        gmtOffset: 46800,
        timestamp: 1647464995,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Palmer',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Rothera',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Syowa',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Troll',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        zoneName: 'Antarctica/Vostok',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'SJ',
        countryName: 'Svalbard and Jan Mayen',
        zoneName: 'Arctic/Longyearbyen',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'YE',
        countryName: 'Yemen',
        zoneName: 'Asia/Aden',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        zoneName: 'Asia/Almaty',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'JO',
        countryName: 'Jordan',
        zoneName: 'Asia/Amman',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Anadyr',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        zoneName: 'Asia/Aqtau',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        zoneName: 'Asia/Aqtobe',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'TM',
        countryName: 'Turkmenistan',
        zoneName: 'Asia/Ashgabat',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        zoneName: 'Asia/Atyrau',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'IQ',
        countryName: 'Iraq',
        zoneName: 'Asia/Baghdad',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'BH',
        countryName: 'Bahrain',
        zoneName: 'Asia/Bahrain',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'AZ',
        countryName: 'Azerbaijan',
        zoneName: 'Asia/Baku',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'TH',
        countryName: 'Thailand',
        zoneName: 'Asia/Bangkok',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Barnaul',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'LB',
        countryName: 'Lebanon',
        zoneName: 'Asia/Beirut',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'KG',
        countryName: 'Kyrgyzstan',
        zoneName: 'Asia/Bishkek',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'BN',
        countryName: 'Brunei Darussalam',
        zoneName: 'Asia/Brunei',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Chita',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'MN',
        countryName: 'Mongolia',
        zoneName: 'Asia/Choibalsan',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'LK',
        countryName: 'Sri Lanka',
        zoneName: 'Asia/Colombo',
        gmtOffset: 19800,
        timestamp: 1647437995,
      },
      {
        countryCode: 'SY',
        countryName: 'Syrian Arab Republic',
        zoneName: 'Asia/Damascus',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'BD',
        countryName: 'Bangladesh',
        zoneName: 'Asia/Dhaka',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'TL',
        countryName: 'Timor-Leste',
        zoneName: 'Asia/Dili',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'AE',
        countryName: 'United Arab Emirates',
        zoneName: 'Asia/Dubai',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'TJ',
        countryName: 'Tajikistan',
        zoneName: 'Asia/Dushanbe',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'CY',
        countryName: 'Cyprus',
        zoneName: 'Asia/Famagusta',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'PS',
        countryName: 'Palestine, State of',
        zoneName: 'Asia/Gaza',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'PS',
        countryName: 'Palestine, State of',
        zoneName: 'Asia/Hebron',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'VN',
        countryName: 'Viet Nam',
        zoneName: 'Asia/Ho_Chi_Minh',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'HK',
        countryName: 'Hong Kong',
        zoneName: 'Asia/Hong_Kong',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'MN',
        countryName: 'Mongolia',
        zoneName: 'Asia/Hovd',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Irkutsk',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'ID',
        countryName: 'Indonesia',
        zoneName: 'Asia/Jakarta',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'ID',
        countryName: 'Indonesia',
        zoneName: 'Asia/Jayapura',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'IL',
        countryName: 'Israel',
        zoneName: 'Asia/Jerusalem',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'AF',
        countryName: 'Afghanistan',
        zoneName: 'Asia/Kabul',
        gmtOffset: 16200,
        timestamp: 1647434395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Kamchatka',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'PK',
        countryName: 'Pakistan',
        zoneName: 'Asia/Karachi',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'NP',
        countryName: 'Nepal',
        zoneName: 'Asia/Kathmandu',
        gmtOffset: 20700,
        timestamp: 1647438895,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Khandyga',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'IN',
        countryName: 'India',
        zoneName: 'Asia/Kolkata',
        gmtOffset: 19800,
        timestamp: 1647437995,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Krasnoyarsk',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'MY',
        countryName: 'Malaysia',
        zoneName: 'Asia/Kuala_Lumpur',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'MY',
        countryName: 'Malaysia',
        zoneName: 'Asia/Kuching',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'KW',
        countryName: 'Kuwait',
        zoneName: 'Asia/Kuwait',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'MO',
        countryName: 'Macao',
        zoneName: 'Asia/Macau',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Magadan',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'ID',
        countryName: 'Indonesia',
        zoneName: 'Asia/Makassar',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'PH',
        countryName: 'Philippines',
        zoneName: 'Asia/Manila',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'OM',
        countryName: 'Oman',
        zoneName: 'Asia/Muscat',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'CY',
        countryName: 'Cyprus',
        zoneName: 'Asia/Nicosia',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Novokuznetsk',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Novosibirsk',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Omsk',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        zoneName: 'Asia/Oral',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'KH',
        countryName: 'Cambodia',
        zoneName: 'Asia/Phnom_Penh',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'ID',
        countryName: 'Indonesia',
        zoneName: 'Asia/Pontianak',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'KP',
        countryName: "Korea (Democratic People's Republic of)",
        zoneName: 'Asia/Pyongyang',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'QA',
        countryName: 'Qatar',
        zoneName: 'Asia/Qatar',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        zoneName: 'Asia/Qostanay',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        zoneName: 'Asia/Qyzylorda',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'SA',
        countryName: 'Saudi Arabia',
        zoneName: 'Asia/Riyadh',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Sakhalin',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'UZ',
        countryName: 'Uzbekistan',
        zoneName: 'Asia/Samarkand',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'KR',
        countryName: 'Korea, Republic of',
        zoneName: 'Asia/Seoul',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'CN',
        countryName: 'China',
        zoneName: 'Asia/Shanghai',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'SG',
        countryName: 'Singapore',
        zoneName: 'Asia/Singapore',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Srednekolymsk',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'TW',
        countryName: 'Taiwan, Province of China',
        zoneName: 'Asia/Taipei',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'UZ',
        countryName: 'Uzbekistan',
        zoneName: 'Asia/Tashkent',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'GE',
        countryName: 'Georgia',
        zoneName: 'Asia/Tbilisi',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'IR',
        countryName: 'Iran (Islamic Republic of)',
        zoneName: 'Asia/Tehran',
        gmtOffset: 12600,
        timestamp: 1647430795,
      },
      {
        countryCode: 'BT',
        countryName: 'Bhutan',
        zoneName: 'Asia/Thimphu',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'JP',
        countryName: 'Japan',
        zoneName: 'Asia/Tokyo',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Tomsk',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'MN',
        countryName: 'Mongolia',
        zoneName: 'Asia/Ulaanbaatar',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'CN',
        countryName: 'China',
        zoneName: 'Asia/Urumqi',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Ust-Nera',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'LA',
        countryName: "Lao People's Democratic Republic",
        zoneName: 'Asia/Vientiane',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Vladivostok',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Yakutsk',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'MM',
        countryName: 'Myanmar',
        zoneName: 'Asia/Yangon',
        gmtOffset: 23400,
        timestamp: 1647441595,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Asia/Yekaterinburg',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'AM',
        countryName: 'Armenia',
        zoneName: 'Asia/Yerevan',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'PT',
        countryName: 'Portugal',
        zoneName: 'Atlantic/Azores',
        gmtOffset: -3600,
        timestamp: 1647414595,
      },
      {
        countryCode: 'BM',
        countryName: 'Bermuda',
        zoneName: 'Atlantic/Bermuda',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'ES',
        countryName: 'Spain',
        zoneName: 'Atlantic/Canary',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'CV',
        countryName: 'Cabo Verde',
        zoneName: 'Atlantic/Cape_Verde',
        gmtOffset: -3600,
        timestamp: 1647414595,
      },
      {
        countryCode: 'FO',
        countryName: 'Faroe Islands',
        zoneName: 'Atlantic/Faroe',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'PT',
        countryName: 'Portugal',
        zoneName: 'Atlantic/Madeira',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'IS',
        countryName: 'Iceland',
        zoneName: 'Atlantic/Reykjavik',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'GS',
        countryName: 'South Georgia and the South Sandwich Islands',
        zoneName: 'Atlantic/South_Georgia',
        gmtOffset: -7200,
        timestamp: 1647410995,
      },
      {
        countryCode: 'SH',
        countryName: 'Saint Helena, Ascension and Tristan da Cunha',
        zoneName: 'Atlantic/St_Helena',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'FK',
        countryName: 'Falkland Islands (Malvinas)',
        zoneName: 'Atlantic/Stanley',
        gmtOffset: -10800,
        timestamp: 1647407395,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Adelaide',
        gmtOffset: 37800,
        timestamp: 1647455995,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Brisbane',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Broken_Hill',
        gmtOffset: 37800,
        timestamp: 1647455995,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Darwin',
        gmtOffset: 34200,
        timestamp: 1647452395,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Eucla',
        gmtOffset: 31500,
        timestamp: 1647449695,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Hobart',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Lindeman',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Lord_Howe',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Melbourne',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Perth',
        gmtOffset: 28800,
        timestamp: 1647446995,
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        zoneName: 'Australia/Sydney',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'NL',
        countryName: 'Netherlands',
        zoneName: 'Europe/Amsterdam',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'AD',
        countryName: 'Andorra',
        zoneName: 'Europe/Andorra',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Astrakhan',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'GR',
        countryName: 'Greece',
        zoneName: 'Europe/Athens',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'RS',
        countryName: 'Serbia',
        zoneName: 'Europe/Belgrade',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'DE',
        countryName: 'Germany',
        zoneName: 'Europe/Berlin',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'SK',
        countryName: 'Slovakia',
        zoneName: 'Europe/Bratislava',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'BE',
        countryName: 'Belgium',
        zoneName: 'Europe/Brussels',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'RO',
        countryName: 'Romania',
        zoneName: 'Europe/Bucharest',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'HU',
        countryName: 'Hungary',
        zoneName: 'Europe/Budapest',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'DE',
        countryName: 'Germany',
        zoneName: 'Europe/Busingen',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'MD',
        countryName: 'Moldova, Republic of',
        zoneName: 'Europe/Chisinau',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'DK',
        countryName: 'Denmark',
        zoneName: 'Europe/Copenhagen',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'IE',
        countryName: 'Ireland',
        zoneName: 'Europe/Dublin',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'GI',
        countryName: 'Gibraltar',
        zoneName: 'Europe/Gibraltar',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'GG',
        countryName: 'Guernsey',
        zoneName: 'Europe/Guernsey',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'FI',
        countryName: 'Finland',
        zoneName: 'Europe/Helsinki',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'IM',
        countryName: 'Isle of Man',
        zoneName: 'Europe/Isle_of_Man',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'TR',
        countryName: 'Turkey',
        zoneName: 'Europe/Istanbul',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'JE',
        countryName: 'Jersey',
        zoneName: 'Europe/Jersey',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Kaliningrad',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'UA',
        countryName: 'Ukraine',
        zoneName: 'Europe/Kiev',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Kirov',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'PT',
        countryName: 'Portugal',
        zoneName: 'Europe/Lisbon',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'SI',
        countryName: 'Slovenia',
        zoneName: 'Europe/Ljubljana',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'GB',
        countryName: 'United Kingdom of Great Britain and Northern Ireland',
        zoneName: 'Europe/London',
        gmtOffset: 0,
        timestamp: 1647418195,
      },
      {
        countryCode: 'LU',
        countryName: 'Luxembourg',
        zoneName: 'Europe/Luxembourg',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'ES',
        countryName: 'Spain',
        zoneName: 'Europe/Madrid',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'MT',
        countryName: 'Malta',
        zoneName: 'Europe/Malta',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'AX',
        countryName: 'Åland Islands',
        zoneName: 'Europe/Mariehamn',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'BY',
        countryName: 'Belarus',
        zoneName: 'Europe/Minsk',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'MC',
        countryName: 'Monaco',
        zoneName: 'Europe/Monaco',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Moscow',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'NO',
        countryName: 'Norway',
        zoneName: 'Europe/Oslo',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'FR',
        countryName: 'France',
        zoneName: 'Europe/Paris',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'ME',
        countryName: 'Montenegro',
        zoneName: 'Europe/Podgorica',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'CZ',
        countryName: 'Czechia',
        zoneName: 'Europe/Prague',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'LV',
        countryName: 'Latvia',
        zoneName: 'Europe/Riga',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'IT',
        countryName: 'Italy',
        zoneName: 'Europe/Rome',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Samara',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'SM',
        countryName: 'San Marino',
        zoneName: 'Europe/San_Marino',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'BA',
        countryName: 'Bosnia and Herzegovina',
        zoneName: 'Europe/Sarajevo',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Saratov',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'UA',
        countryName: 'Ukraine',
        zoneName: 'Europe/Simferopol',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'MK',
        countryName: 'North Macedonia',
        zoneName: 'Europe/Skopje',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'BG',
        countryName: 'Bulgaria',
        zoneName: 'Europe/Sofia',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'SE',
        countryName: 'Sweden',
        zoneName: 'Europe/Stockholm',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'EE',
        countryName: 'Estonia',
        zoneName: 'Europe/Tallinn',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'AL',
        countryName: 'Albania',
        zoneName: 'Europe/Tirane',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Ulyanovsk',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'UA',
        countryName: 'Ukraine',
        zoneName: 'Europe/Uzhgorod',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'LI',
        countryName: 'Liechtenstein',
        zoneName: 'Europe/Vaduz',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'VA',
        countryName: 'Holy See',
        zoneName: 'Europe/Vatican',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'AT',
        countryName: 'Austria',
        zoneName: 'Europe/Vienna',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'LT',
        countryName: 'Lithuania',
        zoneName: 'Europe/Vilnius',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'RU',
        countryName: 'Russian Federation',
        zoneName: 'Europe/Volgograd',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'PL',
        countryName: 'Poland',
        zoneName: 'Europe/Warsaw',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'HR',
        countryName: 'Croatia',
        zoneName: 'Europe/Zagreb',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'UA',
        countryName: 'Ukraine',
        zoneName: 'Europe/Zaporozhye',
        gmtOffset: 7200,
        timestamp: 1647425395,
      },
      {
        countryCode: 'CH',
        countryName: 'Switzerland',
        zoneName: 'Europe/Zurich',
        gmtOffset: 3600,
        timestamp: 1647421795,
      },
      {
        countryCode: 'MG',
        countryName: 'Madagascar',
        zoneName: 'Indian/Antananarivo',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'IO',
        countryName: 'British Indian Ocean Territory',
        zoneName: 'Indian/Chagos',
        gmtOffset: 21600,
        timestamp: 1647439795,
      },
      {
        countryCode: 'CX',
        countryName: 'Christmas Island',
        zoneName: 'Indian/Christmas',
        gmtOffset: 25200,
        timestamp: 1647443395,
      },
      {
        countryCode: 'CC',
        countryName: 'Cocos (Keeling) Islands',
        zoneName: 'Indian/Cocos',
        gmtOffset: 23400,
        timestamp: 1647441595,
      },
      {
        countryCode: 'KM',
        countryName: 'Comoros',
        zoneName: 'Indian/Comoro',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'TF',
        countryName: 'French Southern Territories',
        zoneName: 'Indian/Kerguelen',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'SC',
        countryName: 'Seychelles',
        zoneName: 'Indian/Mahe',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'MV',
        countryName: 'Maldives',
        zoneName: 'Indian/Maldives',
        gmtOffset: 18000,
        timestamp: 1647436195,
      },
      {
        countryCode: 'MU',
        countryName: 'Mauritius',
        zoneName: 'Indian/Mauritius',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'YT',
        countryName: 'Mayotte',
        zoneName: 'Indian/Mayotte',
        gmtOffset: 10800,
        timestamp: 1647428995,
      },
      {
        countryCode: 'RE',
        countryName: 'Réunion',
        zoneName: 'Indian/Reunion',
        gmtOffset: 14400,
        timestamp: 1647432595,
      },
      {
        countryCode: 'WS',
        countryName: 'Samoa',
        zoneName: 'Pacific/Apia',
        gmtOffset: 46800,
        timestamp: 1647464995,
      },
      {
        countryCode: 'NZ',
        countryName: 'New Zealand',
        zoneName: 'Pacific/Auckland',
        gmtOffset: 46800,
        timestamp: 1647464995,
      },
      {
        countryCode: 'PG',
        countryName: 'Papua New Guinea',
        zoneName: 'Pacific/Bougainville',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'NZ',
        countryName: 'New Zealand',
        zoneName: 'Pacific/Chatham',
        gmtOffset: 49500,
        timestamp: 1647467695,
      },
      {
        countryCode: 'FM',
        countryName: 'Micronesia (Federated States of)',
        zoneName: 'Pacific/Chuuk',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'CL',
        countryName: 'Chile',
        zoneName: 'Pacific/Easter',
        gmtOffset: -18000,
        timestamp: 1647400195,
      },
      {
        countryCode: 'VU',
        countryName: 'Vanuatu',
        zoneName: 'Pacific/Efate',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'TK',
        countryName: 'Tokelau',
        zoneName: 'Pacific/Fakaofo',
        gmtOffset: 46800,
        timestamp: 1647464995,
      },
      {
        countryCode: 'FJ',
        countryName: 'Fiji',
        zoneName: 'Pacific/Fiji',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'TV',
        countryName: 'Tuvalu',
        zoneName: 'Pacific/Funafuti',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'EC',
        countryName: 'Ecuador',
        zoneName: 'Pacific/Galapagos',
        gmtOffset: -21600,
        timestamp: 1647396595,
      },
      {
        countryCode: 'PF',
        countryName: 'French Polynesia',
        zoneName: 'Pacific/Gambier',
        gmtOffset: -32400,
        timestamp: 1647385795,
      },
      {
        countryCode: 'SB',
        countryName: 'Solomon Islands',
        zoneName: 'Pacific/Guadalcanal',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'GU',
        countryName: 'Guam',
        zoneName: 'Pacific/Guam',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'US',
        countryName: 'United States of America',
        zoneName: 'Pacific/Honolulu',
        gmtOffset: -36000,
        timestamp: 1647382195,
      },
      {
        countryCode: 'KI',
        countryName: 'Kiribati',
        zoneName: 'Pacific/Kanton',
        gmtOffset: 46800,
        timestamp: 1647464995,
      },
      {
        countryCode: 'KI',
        countryName: 'Kiribati',
        zoneName: 'Pacific/Kiritimati',
        gmtOffset: 50400,
        timestamp: 1647468595,
      },
      {
        countryCode: 'FM',
        countryName: 'Micronesia (Federated States of)',
        zoneName: 'Pacific/Kosrae',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'MH',
        countryName: 'Marshall Islands',
        zoneName: 'Pacific/Kwajalein',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'MH',
        countryName: 'Marshall Islands',
        zoneName: 'Pacific/Majuro',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'PF',
        countryName: 'French Polynesia',
        zoneName: 'Pacific/Marquesas',
        gmtOffset: -34200,
        timestamp: 1647383995,
      },
      {
        countryCode: 'UM',
        countryName: 'United States Minor Outlying Islands',
        zoneName: 'Pacific/Midway',
        gmtOffset: -39600,
        timestamp: 1647378595,
      },
      {
        countryCode: 'NR',
        countryName: 'Nauru',
        zoneName: 'Pacific/Nauru',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'NU',
        countryName: 'Niue',
        zoneName: 'Pacific/Niue',
        gmtOffset: -39600,
        timestamp: 1647378595,
      },
      {
        countryCode: 'NF',
        countryName: 'Norfolk Island',
        zoneName: 'Pacific/Norfolk',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'NC',
        countryName: 'New Caledonia',
        zoneName: 'Pacific/Noumea',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'AS',
        countryName: 'American Samoa',
        zoneName: 'Pacific/Pago_Pago',
        gmtOffset: -39600,
        timestamp: 1647378595,
      },
      {
        countryCode: 'PW',
        countryName: 'Palau',
        zoneName: 'Pacific/Palau',
        gmtOffset: 32400,
        timestamp: 1647450595,
      },
      {
        countryCode: 'PN',
        countryName: 'Pitcairn',
        zoneName: 'Pacific/Pitcairn',
        gmtOffset: -28800,
        timestamp: 1647389395,
      },
      {
        countryCode: 'FM',
        countryName: 'Micronesia (Federated States of)',
        zoneName: 'Pacific/Pohnpei',
        gmtOffset: 39600,
        timestamp: 1647457795,
      },
      {
        countryCode: 'PG',
        countryName: 'Papua New Guinea',
        zoneName: 'Pacific/Port_Moresby',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'CK',
        countryName: 'Cook Islands',
        zoneName: 'Pacific/Rarotonga',
        gmtOffset: -36000,
        timestamp: 1647382195,
      },
      {
        countryCode: 'MP',
        countryName: 'Northern Mariana Islands',
        zoneName: 'Pacific/Saipan',
        gmtOffset: 36000,
        timestamp: 1647454195,
      },
      {
        countryCode: 'PF',
        countryName: 'French Polynesia',
        zoneName: 'Pacific/Tahiti',
        gmtOffset: -36000,
        timestamp: 1647382195,
      },
      {
        countryCode: 'KI',
        countryName: 'Kiribati',
        zoneName: 'Pacific/Tarawa',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'TO',
        countryName: 'Tonga',
        zoneName: 'Pacific/Tongatapu',
        gmtOffset: 46800,
        timestamp: 1647464995,
      },
      {
        countryCode: 'UM',
        countryName: 'United States Minor Outlying Islands',
        zoneName: 'Pacific/Wake',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
      {
        countryCode: 'WF',
        countryName: 'Wallis and Futuna',
        zoneName: 'Pacific/Wallis',
        gmtOffset: 43200,
        timestamp: 1647461395,
      },
    ];
    let iso2s = data.map((d) => d.countryCode);
    iso2s = iso2s.filter((v, i, a) => a.indexOf(v) === i);
    const countries = await this.country.find({ iso2: iso2s });
    console.log({ c: countries.length, d: data.length });
    // data.map(async (c) => {
    //   const { countryCode, zoneName } = c;
    //   const country = await countries.find((c) => c.iso2 === countryCode);
    //   if (country) {
    //     console.log(countryCode);
    //     country.timeZone = zoneName;
    //     await country.save();
    //   }
    // });
    countries.map(async (c) => {
      const country = data.find((d) => d.countryCode === c.iso2);
      if (country) {
        console.log(country.countryCode);
        c.timeZone = country.zoneName;
        await c.save();
      }
    });
  }
}
