version: '3.4'

services:
  weatherapp:
    image: weatherapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9092:9092
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
